version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    labels:
      - "automerge"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    labels:
      - "automerge"
